[package]
name = "qudag-swarm"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "Swarm coordination and multi-agent system for QuDAG"
documentation = "https://docs.rs/qudag-swarm"
keywords = ["swarm", "multi-agent", "distributed", "coordination"]
categories = ["concurrency", "asynchronous"]

[dependencies]
async-trait = "0.1"
dashmap = "5.5"
futures = "0.3"
parking_lot = "0.12"
rayon = "1.7"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.35", features = ["full"] }
tracing = "0.1"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"
tokio-test = "0.4"

[features]
default = ["optimizations"]
optimizations = ["async-coordination"]
async-coordination = []
full-optimizations = ["optimizations"]