[package]
name = "qudag-exchange-api"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "qudag-exchange-server"
path = "src/main.rs"

[dependencies]
qudag-exchange-core = { path = "../core" }

axum = { workspace = true }
axum-extra = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

# Authentication
jsonwebtoken = "9.3"
uuid = { version = "1.11", features = ["v4", "serde"] }

# Rate limiting
governor = "0.8"

# OpenAPI documentation
utoipa = { version = "5.3", features = ["axum_extras"] }
utoipa-swagger-ui = { version = "8.1", features = ["axum"] }

[dev-dependencies]
reqwest = { version = "0.12", features = ["json"] }
tower = { version = "0.5", features = ["util"] }
hyper = "1.5"