[package]
name = "qudag-network"
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true
description = "P2P networking layer for QuDAG - LibP2P with onion routing, dark addressing, and quantum encryption"
documentation = "https://docs.rs/qudag-network"
readme = "README.md"
keywords = ["p2p", "libp2p", "onion-routing", "anonymity", "networking"]
categories = ["network-programming"]

[dependencies]
thiserror.workspace = true
tracing.workspace = true
serde.workspace = true
tokio.workspace = true
futures.workspace = true
serde_json.workspace = true
anyhow.workspace = true
parking_lot.workspace = true
metrics.workspace = true
lru.workspace = true
blake3.workspace = true
uuid.workspace = true
bincode.workspace = true
rand.workspace = true
rand_core.workspace = true

# Networking
libp2p = { version = "0.53", features = ["tcp", "noise", "yamux", "gossipsub", "kad", "identify", "ping", "mdns", "request-response", "relay", "dcutr", "dns", "websocket", "quic", "tls", "metrics", "macros", "tokio", "cbor", "autonat"] }
quinn = "0.11"
rustls = "0.23"
webpki-roots = "0.26"
base64 = "0.21"
void = "1"
either = "1.9"
bs58 = "0.5"
reqwest = { version = "0.11", features = ["json"] }
dashmap = "5.5"
async-trait = "0.1"
ring = "0.17"
curve25519-dalek = "4.1"
zeroize = { version = "1.7", features = ["zeroize_derive"] }
bytes = "1.5"

# Crypto
x25519-dalek = "2.0"
ed25519-dalek = "2.1"
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
sha2 = "0.10"
hkdf = "0.12"

# Other dependencies
qudag-crypto = { path = "../crypto" }

# Compression for message chunking
zstd = "0.13"

[dev-dependencies]
proptest.workspace = true

[features]
default = []
optimizations = ["message-chunking", "adaptive-batching"]
message-chunking = []
adaptive-batching = []
full-optimizations = ["optimizations"]
