version: '3.8'

services:
  # QuDAG Node 1 - Bootstrap node with proper TLS and environment configuration
  node1:
    build:
      context: ..
      dockerfile: qudag-testnet/Dockerfile
    container_name: qudag-node1
    hostname: qudag-node1
    environment:
      # Logging
      - RUST_LOG=info,qudag=debug
      - RUST_BACKTRACE=1
      # Node identification
      - QUDAG_NODE_NAME=local-node1
      - QUDAG_NODE_ID=node1
      - QUDAG_NETWORK_ID=qudag-testnet-local
      # Features
      - QUDAG_DARK_DOMAIN_ENABLED=true
      - QUDAG_QUANTUM_RESISTANCE_ENABLED=true
      # Network configuration
      - QUDAG_P2P_PORT=4001
      - QUDAG_RPC_PORT=8080
      - QUDAG_METRICS_PORT=9090
      - QUDAG_IS_BOOTSTRAP=true
      # Security
      - QUDAG_TLS_ENABLED=true
      - QUDAG_API_AUTH_ENABLED=true
      - QUDAG_CORS_ORIGINS=https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083
      # Paths
      - QUDAG_CONFIG_PATH=/data/qudag/config.toml
      - QUDAG_TLS_CERT_PATH=/data/qudag/tls/cert.pem
      - QUDAG_TLS_KEY_PATH=/data/qudag/tls/key.pem
    secrets:
      - node1_private_key
      - node1_api_token
      - tls_cert
      - tls_key
    ports:
      - "4001:4001"      # P2P
      - "4001:4001/udp"  # P2P UDP
      - "8080:8080"      # RPC (HTTP)
      - "8443:8443"      # RPC (HTTPS)
      - "9090:9090"      # Metrics
    volumes:
      - node1_data:/data/qudag
      - ./configs/node1.toml:/data/qudag/config.toml:ro
      - ./tls:/data/qudag/tls:ro
    networks:
      qudag_net:
        ipv4_address: 172.20.0.10
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/data/qudag/tls/ca.pem", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # QuDAG Node 2 with dynamic bootstrap peer resolution
  node2:
    build:
      context: ..
      dockerfile: qudag-testnet/Dockerfile
    container_name: qudag-node2
    hostname: qudag-node2
    environment:
      # Logging
      - RUST_LOG=info,qudag=debug
      - RUST_BACKTRACE=1
      # Node identification
      - QUDAG_NODE_NAME=local-node2
      - QUDAG_NODE_ID=node2
      - QUDAG_NETWORK_ID=qudag-testnet-local
      # Features
      - QUDAG_DARK_DOMAIN_ENABLED=true
      - QUDAG_QUANTUM_RESISTANCE_ENABLED=true
      # Network configuration
      - QUDAG_P2P_PORT=4001
      - QUDAG_RPC_PORT=8080
      - QUDAG_METRICS_PORT=9090
      # Bootstrap peers will be injected at runtime
      - QUDAG_BOOTSTRAP_PEERS=/ip4/172.20.0.10/tcp/4001/p2p/${BOOTSTRAP_PEER_ID:-12D3KooWBootstrapPeer}
      # Security
      - QUDAG_TLS_ENABLED=true
      - QUDAG_API_AUTH_ENABLED=true
      - QUDAG_CORS_ORIGINS=https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083
      # Paths
      - QUDAG_CONFIG_PATH=/data/qudag/config.toml
      - QUDAG_TLS_CERT_PATH=/data/qudag/tls/cert.pem
      - QUDAG_TLS_KEY_PATH=/data/qudag/tls/key.pem
    secrets:
      - node2_private_key
      - node2_api_token
      - tls_cert
      - tls_key
    ports:
      - "4002:4001"      # P2P
      - "4002:4001/udp"  # P2P UDP
      - "8081:8080"      # RPC (HTTP)
      - "8444:8443"      # RPC (HTTPS)
      - "9091:9090"      # Metrics
    volumes:
      - node2_data:/data/qudag
      - ./configs/node2.toml:/data/qudag/config.toml:ro
      - ./tls:/data/qudag/tls:ro
    networks:
      qudag_net:
        ipv4_address: 172.20.0.11
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/data/qudag/tls/ca.pem", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # QuDAG Node 3
  node3:
    build:
      context: ..
      dockerfile: qudag-testnet/Dockerfile
    container_name: qudag-node3
    hostname: qudag-node3
    environment:
      # Logging
      - RUST_LOG=info,qudag=debug
      - RUST_BACKTRACE=1
      # Node identification
      - QUDAG_NODE_NAME=local-node3
      - QUDAG_NODE_ID=node3
      - QUDAG_NETWORK_ID=qudag-testnet-local
      # Features
      - QUDAG_DARK_DOMAIN_ENABLED=true
      - QUDAG_QUANTUM_RESISTANCE_ENABLED=true
      # Network configuration
      - QUDAG_P2P_PORT=4001
      - QUDAG_RPC_PORT=8080
      - QUDAG_METRICS_PORT=9090
      # Bootstrap peers
      - QUDAG_BOOTSTRAP_PEERS=/ip4/172.20.0.10/tcp/4001/p2p/${BOOTSTRAP_PEER_ID:-12D3KooWBootstrapPeer}
      # Security
      - QUDAG_TLS_ENABLED=true
      - QUDAG_API_AUTH_ENABLED=true
      - QUDAG_CORS_ORIGINS=https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083
      # Paths
      - QUDAG_CONFIG_PATH=/data/qudag/config.toml
      - QUDAG_TLS_CERT_PATH=/data/qudag/tls/cert.pem
      - QUDAG_TLS_KEY_PATH=/data/qudag/tls/key.pem
    secrets:
      - node3_private_key
      - node3_api_token
      - tls_cert
      - tls_key
    ports:
      - "4003:4001"      # P2P
      - "4003:4001/udp"  # P2P UDP
      - "8082:8080"      # RPC (HTTP)
      - "8445:8443"      # RPC (HTTPS)
      - "9092:9090"      # Metrics
    volumes:
      - node3_data:/data/qudag
      - ./configs/node3.toml:/data/qudag/config.toml:ro
      - ./tls:/data/qudag/tls:ro
    networks:
      qudag_net:
        ipv4_address: 172.20.0.12
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/data/qudag/tls/ca.pem", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # QuDAG Node 4
  node4:
    build:
      context: ..
      dockerfile: qudag-testnet/Dockerfile
    container_name: qudag-node4
    hostname: qudag-node4
    environment:
      # Logging
      - RUST_LOG=info,qudag=debug
      - RUST_BACKTRACE=1
      # Node identification
      - QUDAG_NODE_NAME=local-node4
      - QUDAG_NODE_ID=node4
      - QUDAG_NETWORK_ID=qudag-testnet-local
      # Features
      - QUDAG_DARK_DOMAIN_ENABLED=true
      - QUDAG_QUANTUM_RESISTANCE_ENABLED=true
      # Network configuration
      - QUDAG_P2P_PORT=4001
      - QUDAG_RPC_PORT=8080
      - QUDAG_METRICS_PORT=9090
      # Bootstrap peers
      - QUDAG_BOOTSTRAP_PEERS=/ip4/172.20.0.10/tcp/4001/p2p/${BOOTSTRAP_PEER_ID:-12D3KooWBootstrapPeer}
      # Security
      - QUDAG_TLS_ENABLED=true
      - QUDAG_API_AUTH_ENABLED=true
      - QUDAG_CORS_ORIGINS=https://localhost:8080,https://localhost:8081,https://localhost:8082,https://localhost:8083
      # Paths
      - QUDAG_CONFIG_PATH=/data/qudag/config.toml
      - QUDAG_TLS_CERT_PATH=/data/qudag/tls/cert.pem
      - QUDAG_TLS_KEY_PATH=/data/qudag/tls/key.pem
    secrets:
      - node4_private_key
      - node4_api_token
      - tls_cert
      - tls_key
    ports:
      - "4004:4001"      # P2P
      - "4004:4001/udp"  # P2P UDP
      - "8083:8080"      # RPC (HTTP)
      - "8446:8443"      # RPC (HTTPS)
      - "9093:9090"      # Metrics
    volumes:
      - node4_data:/data/qudag
      - ./configs/node4.toml:/data/qudag/config.toml:ro
      - ./tls:/data/qudag/tls:ro
    networks:
      qudag_net:
        ipv4_address: 172.20.0.13
    depends_on:
      node1:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "--cacert", "/data/qudag/tls/ca.pem", "https://localhost:8443/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Prometheus with TLS support
  prometheus:
    image: prom/prometheus:latest
    container_name: qudag-prometheus
    ports:
      - "9094:9090"
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./configs/alerts.yml:/etc/prometheus/alerts.yml:ro
      - prometheus_data:/prometheus
      - ./tls:/etc/prometheus/tls:ro
    networks:
      - qudag_net
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    depends_on:
      - node1
      - node2
      - node3
      - node4

  # Grafana with proper security configuration
  grafana:
    image: grafana/grafana:latest
    container_name: qudag-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_PROTOCOL=https
      - GF_SERVER_CERT_FILE=/etc/grafana/tls/cert.pem
      - GF_SERVER_CERT_KEY=/etc/grafana/tls/key.pem
    volumes:
      - grafana_data:/var/lib/grafana
      - ./configs/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
      - ./configs/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml:ro
      - ./configs/dashboards:/var/lib/grafana/dashboards:ro
      - ./tls:/etc/grafana/tls:ro
    networks:
      - qudag_net
    depends_on:
      - prometheus

# Docker secrets for sensitive data
secrets:
  node1_private_key:
    file: ./.secrets/node_keys/node1_key.pem
  node1_api_token:
    file: ./.secrets/api_tokens/node1_token.txt
  node2_private_key:
    file: ./.secrets/node_keys/node2_key.pem
  node2_api_token:
    file: ./.secrets/api_tokens/node2_token.txt
  node3_private_key:
    file: ./.secrets/node_keys/node3_key.pem
  node3_api_token:
    file: ./.secrets/api_tokens/node3_token.txt
  node4_private_key:
    file: ./.secrets/node_keys/node4_key.pem
  node4_api_token:
    file: ./.secrets/api_tokens/node4_token.txt
  tls_cert:
    file: ./tls/cert.pem
  tls_key:
    file: ./tls/key.pem

volumes:
  node1_data:
  node2_data:
  node3_data:
  node4_data:
  prometheus_data:
  grafana_data:

networks:
  qudag_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24