[package]
name = "kimi-expert-analyzer"
version = "0.1.0"
edition = "2021"
authors = ["rUv <https://github.com/ruvnet>"]
description = "Expert analysis tool for Kimi-K2 to Rust-WASM conversion"
repository = "https://github.com/ruvnet/Synaptic-Mesh"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/ruvnet/Synaptic-Mesh"
documentation = "https://docs.rs/kimi-expert-analyzer"
keywords = ["ai", "neural", "expert", "analysis", "distillation"]
categories = ["science", "algorithms"]

[dependencies]
# Core dependencies
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
thiserror = "1.0"

# Neural network and math
ndarray = "0.15"
numpy = { version = "0.21", optional = true }
candle-core = { version = "0.6", optional = true }
tch = { version = "0.15", optional = true }

# Data processing
csv = "1.3"
rayon = "1.8"
indicatif = "0.17"

# Compression and serialization
bincode = "1.3"
zstd = "0.13"
flate2 = "1.0"

# CLI and logging
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# File I/O and paths
walkdir = "2.4"
tempfile = "3.8"

# Statistical analysis
statrs = "0.16"
plotters = { version = "0.3", optional = true }

# Additional dependencies for CLI and functionality
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6", features = ["v4"] }
serde_yaml = "0.9"
toml = "0.8"

[dev-dependencies]
criterion = "0.5"
proptest = "1.4"

[features]
default = ["pytorch"]
pytorch = ["tch"]
candle-support = ["candle-core"]
numpy-support = ["numpy"]
plotting = ["plotters"]
full = ["pytorch", "candle-support", "numpy-support", "plotting"]

[[bin]]
name = "kimi-analyzer"
path = "src/bin/main.rs"

[lib]
name = "kimi_expert_analyzer"
path = "src/lib.rs"