apiVersion: v1
kind: ConfigMap
metadata:
  name: synaptic-mesh-config
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: config
data:
  network: "mainnet"
  cluster-size: "3"
  log-level: "info"
  p2p-bootstrap-nodes: |
    /ip4/bootstrap1.synaptic-mesh.io/tcp/8081/p2p/QmBootstrap1
    /ip4/bootstrap2.synaptic-mesh.io/tcp/8081/p2p/QmBootstrap2
    /ip4/bootstrap3.synaptic-mesh.io/tcp/8081/p2p/QmBootstrap3
  neural-config: |
    {
      "defaultPort": 8080,
      "defaultNetwork": "mainnet",
      "quantumResistant": true,
      "neuralArchitecture": "adaptive",
      "swarmTopology": "mesh",
      "performance": {
        "maxConnections": 1000,
        "timeoutMs": 30000,
        "retryAttempts": 3
      },
      "security": {
        "enableTLS": true,
        "requireAuth": true,
        "allowedOrigins": ["*"]
      }
    }
  prometheus-config: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    scrape_configs:
    - job_name: 'synaptic-mesh'
      static_configs:
      - targets: ['localhost:9090']
      metrics_path: /metrics
      scrape_interval: 5s
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: synaptic-mesh-wasm
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: wasm
binaryData:
  # WASM modules will be populated during build
  ruv_swarm_wasm_bg.wasm: ""
  ruv_swarm_simd.wasm: ""
  ruv-fann.wasm: ""
  neuro-divergent.wasm: ""
data:
  wasm-manifest.json: |
    {
      "modules": [
        {
          "name": "ruv_swarm_wasm_bg.wasm",
          "description": "Core RUV Swarm WASM module",
          "version": "1.0.0",
          "checksum": ""
        },
        {
          "name": "ruv_swarm_simd.wasm", 
          "description": "SIMD optimized RUV Swarm module",
          "version": "1.0.0",
          "checksum": ""
        },
        {
          "name": "ruv-fann.wasm",
          "description": "Fast Artificial Neural Network WASM",
          "version": "1.0.0", 
          "checksum": ""
        },
        {
          "name": "neuro-divergent.wasm",
          "description": "Neuro-divergent AI patterns",
          "version": "1.0.0",
          "checksum": ""
        }
      ]
    }