apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synaptic-mesh-data
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: fast-ssd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synaptic-mesh-models
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: storage
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: shared-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synaptic-mesh-logs
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: shared-storage