apiVersion: v1
kind: Service
metadata:
  name: synaptic-mesh-core
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: core
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: tcp
spec:
  type: LoadBalancer
  selector:
    app: synaptic-mesh
    component: core
  ports:
  - name: http
    port: 80
    targetPort: 8080
    protocol: TCP
  - name: https
    port: 443
    targetPort: 8080
    protocol: TCP
  - name: p2p
    port: 8081
    targetPort: 8081
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: synaptic-mesh-core-internal
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: core
spec:
  type: ClusterIP
  selector:
    app: synaptic-mesh
    component: core
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  - name: p2p
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: synaptic-mesh-worker
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: worker
spec:
  type: ClusterIP
  selector:
    app: synaptic-mesh
    component: worker
  ports:
  - name: worker
    port: 8082
    targetPort: 8082
    protocol: TCP
  clusterIP: None  # Headless service for worker discovery
---
apiVersion: v1
kind: Service
metadata:
  name: synaptic-mesh-metrics
  namespace: synaptic-mesh
  labels:
    app: synaptic-mesh
    component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  selector:
    app: synaptic-mesh
    component: core
  ports:
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP