[package]
name = "kimi-fann-core"
version = "0.1.1"
edition = "2021"
authors = ["Synaptic Neural Mesh Team"]
description = "Micro-expert neural architecture for Kimi-K2 WASM conversion using ruv-FANN"
license = "MIT OR Apache-2.0"
repository = "https://github.com/ruvnet/Synaptic-Neural-Mesh"
keywords = ["neural-networks", "wasm", "ai", "machine-learning", "kimi"]
categories = ["algorithms", "science", "wasm"]

[lib]
crate-type = ["cdylib"]

[dependencies]
# Core neural network engine - using actual ruv-FANN crate
ruv-fann = { version = "0.1.6", features = ["wasm"], default-features = false }

# WebAssembly bindings
wasm-bindgen = "0.2"
js-sys = "0.3"
web-sys = { version = "0.3", features = ["Worker", "MessageEvent", "DedicatedWorkerGlobalScope", "console", "Window"] }

# Serialization and data handling
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde-wasm-bindgen = "0.4"

# Memory management and collections
lru = "0.12"
hashbrown = "0.14"

# Async support for WASM
futures = "0.3"
wasm-bindgen-futures = "0.4"

# Error handling
thiserror = "1.0"
anyhow = "1.0"

# Mathematical operations
num-traits = "0.2"

# Compression for memory optimization
lz4 = "1.24"
flate2 = "1.0"

# Async processing and timing
gloo-timers = { version = "0.3", features = ["futures"] }
futures-channel = "0.3"

# Logging (WASM compatible)
log = { version = "0.4", features = ["std"] }
console_log = "1.0"

# Random number generation for WASM and general use
fastrand = "2.0"

[dependencies.getrandom]
version = "0.2"
features = ["js"]
default-features = false

[dev-dependencies]
env_logger = "0.11"
criterion = { version = "0.5", features = ["html_reports"] }
wasm-bindgen-test = "0.3"
tokio = { version = "1.0", features = ["full"] }
async-std = "1.12"
proptest = "1.4"
tempfile = "3.8"

[features]
default = ["reasoning", "coding", "language", "mathematics", "tool-use", "context"]

# Expert domain features
reasoning = []
coding = []
language = []
mathematics = []
tool-use = []
context = []

# Performance features
simd = []
gpu = []

# Development features
debug = ["log/max_level_debug"]

[profile.release]
opt-level = "z"          # Optimize for size
lto = true               # Enable LTO for cdylib
panic = "abort"         # No unwinding
codegen-units = 1       # Better optimization
strip = true            # Strip symbols
debug = false           # No debug info
overflow-checks = false # No overflow checks
incremental = false     # Better optimization

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

[[example]]
name = "micro_expert_demo"
path = "examples/micro_expert_demo.rs"