# Configuration file for cargo-deny
# https://embarkstudios.github.io/cargo-deny/

[graph]
# The graph table configures how the dependency graph is constructed and thus
# which crates the checks are performed over
all-features = false
no-default-features = false

[advisories]
# The advisories section configures how the `cargo deny check advisories` command works
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
vulnerability = "deny"
unmaintained = "warn"
yanked = "warn"
notice = "warn"
ignore = [
    # Ignore specific advisories if needed
]

[licenses]
# The licenses section configures how the `cargo deny check licenses` command works
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
deny = [
    # Copyleft licenses we don't want
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
]
copyleft = "warn"
allow-osi-fsf-free = "neither"
default = "deny"
confidence-threshold = 0.8

# Allow specific crates with potentially problematic licenses
[[licenses.exceptions]]
allow = ["Unicode-DFS-2016"]
name = "unicode-ident"

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"

# List of crates that are allowed to have multiple versions
skip = [
    { name = "windows-sys", version = "*" },
    { name = "windows-targets", version = "*" },
    { name = "syn", version = "*" },
]

# List of explicitly disallowed crates
deny = [
    # Crates with known security issues
    { name = "openssl", version = "<0.10.45" },
    # Unmaintained crates
    { name = "chrono", version = "<0.4.19" },
]

[sources]
# Lint level for what to happen when a crate from a crate registry that is
# not in the allow list is encountered
unknown-registry = "warn"
unknown-git = "warn"

# List of allowed registries
allow-registry = ["https://github.com/rust-lang/crates.io-index"]

# List of allowed Git repositories
allow-git = []