# Fly.io Configuration for QuDAG Exchange Validator Node
# This node focuses on transaction validation and consensus participation

app = "qudag-testnet-validator"
primary_region = "ord"

[build]
  dockerfile = "Dockerfile"

[env]
  # Node Configuration
  NODE_ID = "validator-node"
  NODE_TYPE = "validator"
  NETWORK_MODE = "testnet"
  
  # Bootstrap Configuration
  BOOTSTRAP_PEERS = "bootstrap-node.internal:4001,exchange-full-node.internal:4001"
  
  # Exchange Configuration
  QUDAG_EXCHANGE_ENABLED = "true"
  EXCHANGE_GENESIS = "false"
  EXCHANGE_NODE_TYPE = "validator"
  
  # Validator-Specific Configuration
  ENABLE_TRANSACTION_VALIDATION = "true"
  ENABLE_CONSENSUS_PARTICIPATION = "true"
  VALIDATOR_STAKE_MINIMUM = "1000"
  
  # Fee Model Configuration
  FEE_MODEL_ENABLED = "true"
  FEE_SYNC_WITH_NETWORK = "true"
  ENABLE_FEE_VALIDATION = "true"
  
  # Immutable Deployment Configuration
  IMMUTABLE_DEPLOYMENT = "false"
  IMMUTABLE_FOLLOW_NETWORK = "true"
  
  # Exchange Features (Focused on Validation)
  ENABLE_EXCHANGE_VALIDATION = "true"
  ENABLE_SIGNATURE_VERIFICATION = "true"
  ENABLE_DOUBLE_SPEND_DETECTION = "true"
  
  # API Configuration (Limited for Validators)
  ENABLE_EXCHANGE_API = "true"
  EXCHANGE_API_PORT = "8081"
  API_READ_ONLY = "true"
  
  # Performance Tuning for Validation
  VALIDATION_THREAD_COUNT = "4"
  SIGNATURE_VERIFICATION_BATCH_SIZE = "100"
  
  # Logging and Monitoring
  RUST_LOG = "info,qudag_exchange=debug,qudag_validator=debug"

# QuDAG DAG and consensus data
[[mounts]]
  destination = "/data"
  source = "qudag_data"

# Exchange validation data (smaller for validators)
[[mounts]]
  destination = "/exchange"
  source = "exchange_data"

# Cryptographic keys (separate volume for security)
[[mounts]]
  destination = "/keys"
  source = "exchange_keys"

# P2P Networking (libp2p)
[[services]]
  internal_port = 4001
  protocol = "tcp"
  
  [[services.ports]]
    port = 4001

# QuDAG Node RPC API
[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    port = 80
    handlers = ["http"]
  
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

# Exchange API (Read-Only)
[[services]]
  internal_port = 8081
  protocol = "tcp"
  
  [[services.ports]]
    port = 8081
    handlers = ["http"]

# Metrics and Monitoring
[[services]]
  internal_port = 9090
  protocol = "tcp"
  
  [[services.ports]]
    port = 9090

[experimental]
  cmd = ["./qudag", "start", "--config", "/config/validator.toml", "--enable-exchange", "--validator-mode"]

[deploy]
  release_command = "./qudag validator register --stake 1000"